name: Scraping Data

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          
      - name: Install dependencies
        run: |
          npm install puppeteer
          npm install fs path
        working-directory: 'Linkedin Profile Scraper'
          
      - name: Execute script
        run: node people_profile_scraper.js
        working-directory: 'Linkedin Profile Scraper'
        
      - name: Commit and Push Changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "Auto commit"
          git push
